export const init = {
    _id : '',
    id : '',
    title : '',
    description: '',
    category: '',
    price: '',
    discountPercentage: '',
    rating: '',
    stock: '',
    brand: '',
    shippingInformation: '',
    availabilityStatus: '',
    images: '',
    thumbnail: '',
}